# Generated by Django 6.1.1 on 2026-09-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('minimum_distance', models.DecimalField(decimal_places=2, help_text='Minimum distance in kilometers', max_digits=6)),
                ('maximum_distance', models.DecimalField(decimal_places=2, help_text='Maximum distance in kilometers', max_digits=6)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['minimum_distance'],
            },
        ),
    ]
