services:
  - type: web
    name: sweet-snacks-bot
    runtime: python
    plan: free

    buildCommand: ./build.sh

    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT

    healthCheckPath: /admin/login/

    envVars:
      - key: PYTHON_VERSION
        value: 3.14.5

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        sync: false

      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: PAYMENT_KEY_ID
        sync: false

      - key: PAYMENT_KEY_SECRET
        sync: false