services:
  - type: web
    name: sweets-delivery-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        fromService:
          name: sweets-delivery-bot
          property: url